name: Deploy HTML to GitHub Pages

on:
  push:
     branches:
         - master # or 'main' if your branxh is named main

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup pages
           uses: actions/configure-pages@v3

         - name: Upload site to GitHub Pages
           uses: actions/upload-pages-artifact@v2
           with:
              path: 'site'

         - name: Deploay to GitHub pages
           uses: actions/deploy-pages@v2
      
